name: flutter_boiler
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5

  # manager state
  provider: ^6.0.3

  #navigation
  go_router: ^5.0.5

  # config
  flutter_launcher_icons: "^0.10.0"
  flutter_native_splash: ^2.2.11
  get_it: ^7.2.0 # for injection
  flutter_dotenv: ^5.0.2

  # data
  shared_preferences: ^2.0.15
  dio: ^4.0.6

  # UI
  skeletons: ^0.0.3
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  smooth_page_indicator: ^1.0.0+2

  webview_flutter: ^3.0.4
  carousel_slider: ^4.1.1

  # chart
  candlesticks:
    path: ./package/candlesticks

  fl_chart: ^0.55.2

  ably_flutter: ^1.2.15
  web_socket_channel: ^2.2.0

  secure_app_switcher: ^0.1.0+1
  live_activities:
    path: ./package/live_activities
  flutter_html: ^3.0.0-alpha.6

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  curved_navigation_bar: ^1.0.3
  convex_bottom_bar: ^3.1.0+1
  flutter_multi_formatter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: CreditCard
      fonts:
        - asset: assets/font/CREDC.ttf
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 500

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/lang/
    - assets/launcher_icon/
    - assets/mock/
    - assets/icons/
    - .env.dev
    - .env.prod
