name: Release

on:
  push:
    branches:
      - "main"

jobs:
  deploy_android:
    runs-on: self-hosted

    steps:
      - name: Cleanup after build
        uses: git9527/clean-up-action@v1
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11.x"

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.3"

#       - name: Install depenencis
#         run: |
#           export LC_ALL=en_US.UTF-8
#           export LANG=en_US.UTF-8
#           flutter --version
#           flutter pub get
#           flutter build apk --flavor prod -t lib/main_prod.dart

#       - run: fastlane android deploy_prod

#         env:
#           DIAWI_TOKEN: "${{ secrets.DIAWI_TOKEN }}"
#           EMAIL_CALLBACK: "${{ secrets.EMAIL_CALLBACK }}"
